[package]
name = "rtracker"
version = "0.7.0"
authors = ["Justin Noah <justinnoah@gmail.com>"]
license = "Apache-2.0"
keywords = ["bittorrent", "torrent", "tracker"]
categories = ["command-line-utilities"]

[dependencies]
bincode         = "0.7"
byteorder       = "1.0"
chrono          = "0.3"
docopt          = "0.7"
env_logger      = "0.4"
log             = "0.3"
r2d2            = "0.7"
r2d2_sqlite     = "0.2"
rand            = "0.3"
rustc-serialize = "0.3"
rust-ini        = "0.10"
serde           = "0.9"
serde_derive    = "0.9"

[dependencies.rusqlite]
version = "0.11"
default-features = false
features = ["chrono", "serde_json"]

[[bin]]
name = "rtracker"
path = "src/main.rs"

[badges]
travis-ci = { repository = "justinnoah/rtracker" }
appveyor = { repository = "justinnoah/rtracker" }
